config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
      devise_for :users
      mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
      root 'homepage#index'
      resources :listings
      resources :contacts
      namespace :account do
        resources :contacts
        resources :messages
        resources :user, only: [:index, :update]
      end
    end
    resources :listings
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :listings

  rails_admin

end

app/models/contact.rb
class Contact < ApplicationRecord

  belongs_to :user

  belongs_to :listing

  def self.seller_contacts_for(user_id)
    Contact.joins('LEFT JOIN listings ON listings.id = contacts.listing_id')
          .where(['listings.id = ?', user_id])
          .order('contacts.created_at DESC')
  end

  def self.buyer_messages_from(user_id)
    Contact.where(['user_id = ?',user_id]).order('contacts.created_at DESC')
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :category
  mount_uploader :picture, AttachmentUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listing

  # Editable on panel
  rails_admin
end

app/controllers/account/account_controller.rb
class Account::AccountController < ApplicationController
  before_action :authenticate_user!
  layout "account"
end

app/controllers/account/contacts_controller.rb
class Account::ContactsController < Account::AccountController
  def index

    @contacts = Contact.seller_contacts_for(current_user.id)

  end
end

app/controllers/account/messages_controller.rb
class Account::MessagesController < Account::AccountController
  def index
    @messages = Contact.buyer_messages_from(current_user.id)
  end
end

app/controllers/account/user_controller.rb
class Account::UserController < Account::AccountController

  before_action :set_user, only: [:update]

  def index
    @user = current_user
  end

  # PATCH/PUT /account/user/1
  # PATCH/PUT /account/user/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to account_user_index_path, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :index }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:firstname, :lastname, :password, :password_confirmation)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 I18n.locale= :fr
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_listing, only: [:show]

  # GET /contacts/1.json
  def show
  end

  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
  end

  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:message, :listing_id, :user_id).merge(:user_id => current_user.id)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  
  def index
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

before_action :set_listing, only: [:show, :edit, :update, :destroy]


  def index
    @listings = Listing.all
    if params[:search] or params[:category_id]
      @listings = Listing.search(params).order("created_at DESC")
    else
      @listings = Listing.all.order('created_at DESC')
    end
  end

  def show
  end

  def new
    @listing = Listing.new
    @categories = Category.all
  end

  def create
    @listing = Listing.new(task_params)
  end

  def update
      respond_to do |format|
        if @listing.update(task_params)
          format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
          format.json { render :show, status: :ok, location: @listing }
        else
          format.html { render :edit }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @listing.destroy
      respond_to do |format|
        format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

  def task_params
    params.require(:listing).permit(:title, :desc, :price, :picture, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def locale_select(lang)
    out = "<select class='form-control pull-right language' data-do='setLocale'>"
    I18n.available_locales.each do|loc|
     out += "<option value='#{url_for(locale: loc.to_s)}' #{'selected' if lang == loc }>#{loc}</option>"
    end
    out += "</select>"
    out.html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/homepage/index.html.haml
.row
  .col-xs-8.col-xs-offset-2.search
    %h2= t('main_baseline')
    = form_tag listings_path, method: :get, class: 'form form-horizontal' do
      .form-group
        .col-xs-10
          = text_field_tag 'keyword', nil, class: 'form-control', placeholder: t('seach_placeholder')
        .col-xs-2
          = submit_tag t('search'), class: 'btn btn-success'

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css">

  <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">

    <title>Listings</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class ='<%= params[:controller] %>'>
    <div class="header">

    <%= render partial: 'account/shared/nav' %>

    </div>
    <div class='container content'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css">

  <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">

    <title>Listings</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class ='<%= params[:controller] %>'>
    <div class="header">

    <%= render partial: 'shared/header' %>

    </div>
    <div class='container content'>
    <%= yield %>
    </div>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" %>
  </body>
</html>

app/views/listings/edit.html.haml
.row
  .col-xs-8.col-xs-offset-2
    %h1 Editing listing

= link_to 'New', @listing
\|
= link_to 'Back', listings_path

app/views/listings/index.html.haml
-@listings.each do |listing|
  .row
    .col-xs-12.listing
      %h3=listing.title
      %p.date
        = l(listing.created_at)
        %span.badge
          /= link_to listing.category.name, listings_path(:category_id => listing.category.id)
      .row
        .col-xs-2
          =image_tag listing.picture, width: 300, class: 'img-responsive'
        .col-xs-10
          %p
            = listing.desc
            .clearfix
              %br
          %span.price
            =listing.price
            €
          - if user_signed_in?
            = link_to t('contact'), new_user_session_path, class: 'btn btn-primary pull-right', 'data-do' => 'showContactModal', 'data-id' => listing.id, 'data-user' => current_user.id
          - else
            = link_to t('contact'), new_user_session_path, class: 'btn btn-primary pull-right', 'data-do' => 'showContactModal', 'data-id' => listing.id, 'data-user' => ''

= render :partial => 'listings/modals/contact'

app/views/listings/modals/_contact.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", "data-is" => "contactModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      = form_tag contacts_path method: 'post', data: {is: 'contactForm'} do
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#myModalLabel.modal-title Contact seller
        .modal-body
          .form-group
            %label= t('your message')
            = text_area_tag 'message', nil, class: 'form-control'
        .modal-footer
          = submit_tag 'Send', class: 'btn btn-primary pull-right'

app/views/listings/new.html.haml
.container.content
  .row
    .col-xs-6.col-xs-offset-3
      %h2=t('create listing')
  .row 
    .col-xs-6.col-xs-offset-2.well
    
      = form_for @listing, class: 'form' do |f|
        - if @listing.errors.any?
          #error_explanation
            %h2
              = pluralize(listing.errors.count, "error")
              prohibited this task from being saved:
            %ul
              - listing.errors.full_messages.each do |message|
                %li= message
        .field
          = f.label :title
          = f.text_field :title, class: 'form-group'
        .field
          = f.label :desc
          = f.text_area :desc, class: 'form-group'
        .field
          = f.label :price
          = f.text_field :price, class: 'form-group'
        .field
          = f.label :picture
          = f.file_field :picture, class: 'form-group'
        .field
          = f.label :category_id
          %select{name: 'listing[category_id]'}
            - Category.all.each do |cat|
              %option{value: cat.id}= cat.name
        .actions
          = f.submit class: 'btn btn-default'

app/views/listings/show.html.haml
%p#notice= notice

%h4
  Affichage de la tache #
  = @listing.id

.row
  .col.s12
    .card.horizontal
      .card-image
        =image_tag @listing.picture, height:200
      .card-stacked
        .card-content
          .card-title
            =@listing.title
          %p
            = @listing.desc

= link_to 'Back', listings_path, :class => 'btn grey waves-effect waves-light'

app/views/shared/_header.html.haml
.container
  .row.top
    .col-xs-2
      %h1.title= link_to("Listings", root_path)
    .col-xs-10.pull-right
      = link_to t('create_listing'), new_listing_path, :class => 'btn btn-success pull-right'
      = locale_select(I18n.locale)
      - if user_signed_in?
        = link_to t('my_account'), account_contacts_path, class: "my-account pull-right"
        = link_to t('sign_out'), destroy_user_session_path, class: "logout pull-right", 'data-method' => 'delete'
      - else
        = link_to t('sign_in'), user_session_path, class: "my-account pull-right"

app/views/user/index.html.haml
- if @user.errors.any?
  .row
    .col-xs-8.col-xs-offset-2.errors
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  %br/
.row
  .col-xs-6.well
    = form_for @user, url: account_user_path(current_user.id), method: 'patch' do |f|
      .form-group
        = f.label :email, class:'form-label required'
        = f.text_field :email, class:'form-control'

      .form-group
        = f.label :firstname, t('firstname'), class:'form-label required'
        = f.text_field :firstname, class:'form-control'

      .form-group
        = f.label :lastname, t('lastname'), class:'form-label required'
        = f.text_field :lastname, class:'form-control'

      .form-group
        = f.submit t('save'), class:'btn btn-primary pull-right'

  .col-xs-5.col-xs-offset-1.well
    = form_for @user, url: account_user_path(@user), method: 'put' do |f|
      = f.hidden_field :reset_password_token
      .form-group
        = f.label :password, t('new_password'), class:'form-label required'
        = f.password_field :password, autocomplete: "off", class:'form-control'
      .form-group
        = f.label :password_confirmation, t('confirm_new_password'), class:'form-label required'
        = f.password_field :password_confirmation, autocomplete: "off", class:'form-control'
      .form-group
        = f.submit t('save'), class:'btn btn-primary pull-right'